#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-warden
Version  : 1.2.6
Release  : 8
URL      : https://rubygems.org/downloads/warden-1.2.6.gem
Source0  : https://rubygems.org/downloads/warden-1.2.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rack
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
Please see the "Warden Wiki":http://wiki.github.com/hassox/warden for overview documentation.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n warden-1.2.6
gem spec %{SOURCE0} -l --ruby > rubygem-warden.gemspec

%build
gem build rubygem-warden.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
warden-1.2.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/warden-1.2.6
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/warden-1.2.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/History.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/mixins/common.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/session_serializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/strategies.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/strategies/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/test/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/test/mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/test/warden_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/lib/warden/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/request_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/fail_with_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/failz.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/invalid.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/pass.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/pass_with_message.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/password.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/helpers/strategies/single.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/authenticated_data_store_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/errors_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/hooks_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/manager_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/scoped_session_serializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/session_serializer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/strategies/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/strategies_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/test/helpers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/test/mock_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/spec/warden/test/test_mode_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/warden-1.2.6/warden.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/warden-1.2.6.gemspec
