#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-warden
Version  : 1.2.3
Release  : 6
URL      : https://rubygems.org/downloads/warden-1.2.3.gem
Source0  : https://rubygems.org/downloads/warden-1.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rack
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
Please see the "Warden Wiki":http://wiki.github.com/hassox/warden for overview documentation.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n warden-1.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-warden.gemspec

%build
gem build rubygem-warden.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
warden-1.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/warden-1.2.3
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/warden-1.2.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/deep_dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/default_strategies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/scope_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/serialize_from_session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/serialize_into_session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/silence_missing_strategies%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Config/strategies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/_after_failed_fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/_before_failure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/_before_logout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/_on_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/after_authentication-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/after_failed_fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/after_fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/after_set_user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/before_failure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/before_logout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/cdesc-Hooks.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Hooks/on_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/call_failure_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/cdesc-Manager.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/intercept_401%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/process_unauthenticated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/serialize_from_session-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Manager/serialize_into_session-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/cdesc-Common.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/raw_session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/reset_session%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/Common/warden_cookies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Mixins/cdesc-Mixins.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/NotAuthenticated/cdesc-NotAuthenticated.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/blank%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/cdesc-Errors.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/clear%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/errors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/full_messages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/Errors/on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/_fetch_strategy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/_perform_authentication-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/asset_request%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/authenticate%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/authenticate%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/authenticate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/authenticated%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/cdesc-Proxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/clear_strategies_cache%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/custom_failure%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/custom_failure%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/errors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/lock%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/logout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/manager-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/session_serializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/set_user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/unauthenticated%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/winning_strategies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Proxy/winning_strategy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/cdesc-SessionSerializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/key_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/SessionSerializer/stored%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/clear%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/custom%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/custom_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/errors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/fail%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/fail-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/halt%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/halted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/pass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/redirect%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/scope-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/store%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/success%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/Base/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/_strategies-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/add-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/cdesc-Strategies.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/clear%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Strategies/update-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/Helpers/cdesc-Helpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/Helpers/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/Helpers/login_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/Helpers/logout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/WardenHelpers/_on_next_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/WardenHelpers/asset_paths%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/WardenHelpers/asset_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/WardenHelpers/cdesc-WardenHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/WardenHelpers/on_next_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/WardenHelpers/test_reset%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/UserNotSet/cdesc-UserNotSet.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/cdesc-Warden.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/Warden/test_mode%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/warden-1.2.3/ri/page-README_textile.ri
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/README.textile
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/hooks.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/mixins/common.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/proxy.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/session_serializer.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/strategies.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/strategies/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/test/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/test/warden_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/lib/warden/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/request_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/strategies/failz.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/strategies/invalid.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/strategies/pass.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/strategies/pass_with_message.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/strategies/password.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/helpers/strategies/single.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/authenticated_data_store_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/config_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/errors_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/hooks_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/manager_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/proxy_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/scoped_session_serializer.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/session_serializer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/strategies/base_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/strategies_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/test/helpers_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/spec/warden/test/test_mode_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/warden-1.2.3/warden.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/warden-1.2.3.gemspec
